---
title: "Exercise: Markdown"
author: "Environmental Data Analytics | John Fay and Luana Lima "
output: pdf_document
geometry: margin=2.54cm
editor_options: 
  chunk_output_type: console
toc: true
---
\listoftables

## Set up the coding environment

```{r setup, warning=FALSE, echo=FALSE}
knitr::opts_chunk$set(include = FALSE) #this is the same as adding a r-chunk command within the {}
#Load packages
library(tidyverse);library(here);library(lubridate)

#Load data
nutrient_data_raw <- read.csv(
  here('Data/Processed_KEY','NTL-LTER_Lake_Nutrients_PeterPaul_Processed.csv'),
  stringsAsFactors = TRUE)

#Fix dates
nutrient_data_raw$sampledate = ymd(nutrient_data_raw$sampledate)

```

The raw daaset has `r nrow(nutrient_data_raw)` rows and `r ncol(nutrient_data_raw)` columns.

^That spits out the numnber of rows and columns from that table. Basically running code within rmd file.

## Wrangle the data

```{r wrangle}
#Subset columns and rows
nutrient_data <- nutrient_data_raw %>% 
  select(-c(lakeid,depth_id,comments)) %>% 
  filter(depth == 0) %>% 
  drop_na()

#Compute summary stats for total nitrogen
nutrient_data_tn <- nutrient_data %>% 
  group_by(lakename) %>% 
  summarize(
    mean_tn_ug = mean(tn_ug),
    min_tn_ug = min(tn_ug),
    max_tn_ug = max(tn_ug),
    sd_tn_ug = sd(tn_ug)
  )
```

\newpage

## Report the summary

```{r kable command, echo=FALSE}
#kable command doesnt always make it look perfect
nutrient_data_tn 
#when you knit this it doesnt actually look like a good table

knitr::kable(nutrient_data_tn)
#this spits out what looks like a table format in Rmd
#there are still weird names but looks way better

knitr::kable(nutrient_data_tn, caption = "Summary of Total Nitrogen") 
#assigns a table number plus the caption (looks kinda like a title)
```

